permissions: write-all
name: Build and Run Golang every 5 minutes and on push

on:
  schedule:
    - cron: '*/5 * * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build Golang program
        run: go build .

      - name: Run Golang program if build succeeded
        if: success()
        run: ./ping

      - name: Commit changes
        if: success() && github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Status data update commit by github actions"
          git push
          
