permissions: write-all
name: Run Golang every 5 minutes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Run Golang script
        run: go run .

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "Auto-commit by GitHub Action"
          git push
          
