permissions: write-all
name: Run Python every 5 minutes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests
        run: python -m pip install requests

      - name: Run Python script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python ping.py $DISCORD_WEBHOOK_URL

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "Auto-commit by GitHub Action"
          git push
          
